### ISSUE TITLE
Error: Format of labels is invalid. It couldn't be coerced to a list. 

### ISSUE THREAD

**Issue by wiebkedrews** [ipa-tys/ROCR#11]
_I would appreciate your help with a recurring problem I encounter when plotting the ROC curve: **Error: Format of labels is invalid. It couldn't be coerced to a list.** Moreover, is there an alternative way to plot the TPR and FPR against each other?_

_Here's my code:_

```
library(quanteda)
library(e1071)
library(SparseM)
library(readtext)

#Twitter_both <- readtext(file="/Twitter_both.csv", text_field="text")

set.seed(123)
tweets50000 <- Twitter_both[sample(nrow(Twitter_both), 50000),]

tweets50000$text <- gsub('@[0-9_A-Za-z]+', '@', tweets50000$text)
twcorpus <- corpus(tweets50000$text)
twdfm <- dfm(twcorpus, remove=stopwords("english"), remove_url=TRUE, 
             ngrams=1:2, verbose=TRUE)
twdfm <- dfm_trim(twdfm, min_docfreq = 5, verbose=TRUE)

training <- sample(1:nrow(tweets50000), floor(.80 * nrow(tweets50000)))
test <- (1:nrow(tweets50000))[1:nrow(tweets50000) %in% training == FALSE]

fit <- tune(svm, train.x=twdfm[training,], 
            train.y=factor(tweets50000$dummy[training]),
            kernel="linear",
            ranges=list(cost=c(0.1, 1.0)),
            decision.values = TRUE)
summary(fit)

bestmodel <- fit$best.model
summary(bestmodel)

library(ROCR)

rocplot = function (pred , truth , ...) {
+predob = prediction (pred , truth )
+perf = performance (predob , "tpr ", "fpr ")
+plot(perf ,...) }

fitted <- attributes(predict(bestmodel, twdfm[training,], decision.values = TRUE))$decision.values
par(mfrow=c(1,2))

rocplot(fitted, twdfm[training, "y"], main="Training Data")

**Error: Format of labels is invalid. It couldn't be coerced to a list.**
```

**Comment by FelixErnst** [comment]
There are two issues with the code you provided

1. 
```
rocplot = function (pred , truth , ...) {
+predob = prediction (pred , truth )
+perf = performance (predob , "tpr ", "fpr ")
+plot(perf ,...) }
```

Contains the `+` character so my guess is, that something might be happening there

2.
`twdfm[training, "y"]` is a `Document-feature matrix` and not a data.frame or something else coercible to a list.

The labels argument must be as stated on the man page `?prediction`, a `A vector, matrix, list, or data frame containing the true class labels`. The `twdfm[training, "y"]` object is not matching these requirements and you must convert this to an apropriate input. Probably you want to do something like: `as.vector(twdfm[training, "y"])`.

Please try this and reopen the issue, if the problem persists.
