### ISSUE TITLE
ROCR::performance throws misleading error if any predictions are NA

### ISSUE THREAD

**Issue by asantucci** [ipa-tys/ROCR#5]
If we pass `ROCR::prediction` a vector of responses containing an NA, then some of our objects such as `n.pos` will be NA when returned from the function. When this object is fed into `ROCR::performance`, we trip an `if` statement that yields `Error: insufficient number of distinct values in response/predictions`.

This error is due to the missing `n.pos` object, not due to insufficient number of distinct predictions...Please consider a different error handling?

**Comment by FelixErnst** [comment]
Should be fixed in https://github.com/ipa-tys/ROCR/commit/25ea0b69a5ee0da21a58c30f2d1de32d5cb7c8d2. Please let me know, if you have the time.

In addition I would like to ask you to provide a reproducable example, if the issue persists. Thank you!
