### ISSUE TITLE
Error: 'predictions' contains NA

### ISSUE THREAD

**Issue by drdataking** [ipa-tys/ROCR#9]
My data set has some NA. I don't have to remove NA under R3.6 and it works fine. But when I upgrade to R4.0, the Error: 'predictions' contains NA message appears with the prediction() function. It works when I switch back to R3.6. It also works after I remove all the NA under R4.0. Do I have to remove NA manually under R4.0 to use the prediction()? I don't think so and I believe it is due to some other reasons. Could you help me on this? Thanks.

**Comment by FelixErnst** [comment]
Yes, you have to remove the `NA` yourself. See #5

This has nothing to do with R 4.0, but with a ROCR version upgrade from `1.0-7` to `1.0.11`.

You can install `1.0-7` from the CRAN archive, if you need to: https://cran.r-project.org/src/contrib/Archive/ROCR/ROCR_1.0-7.tar.gz
